### PR TITLE
mark link header discovery as at risk

### PR DESCRIPTION
**Pull request by elf-pavlik**
As discussed in https://github.com/solid/webid-oidc-spec/issues/18#issuecomment-486453876

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
👍

**Comment by zenomt** [comment]
+1

**Comment by elf-pavlik** [comment]
I understood that @kjetilk currently acts as editor in all spec and merges PRs

**Comment by kjetilk** [comment]
Yeah, at least we're trying to draw up a process around it so that we can get things done :-)

**Comment by michielbdejong** [comment]
@kjetilk I think we have agreement on this one, can you merge this?

**Review by RubenVerborgh — APPROVED** [review]

**Comment by michielbdejong** [comment]
I don't have access to merge this.

**Review by michielbdejong — APPROVED** [review]

**Review by kjetilk — APPROVED** [review]
Noting that @jvasseur proposed a use case where it could be useful, I think the rest of the comments in #18 makes this PR valid. If there are use cases for it, we can work that out even if it is marked at risk.

**Comment by michielbdejong** [comment]
@kjetilk can you merge this?

**Comment by kjetilk** [comment]
Ah, right. We haven't got the labels that we use in solid-spec here, but I think it has had sufficient review time.

**Pull request merged**
