### PR TITLE
Add application-based workflow example

### PR DESCRIPTION
**Pull request by justinwb**
This pull adds an example use case where a given application/agent is permitted to access pod resources on behalf of a given user.

### CODE REVIEW

**Comment by TallTed** [comment]
I think "Identity Provider (OP)" should be  "Identity Provider (IdP)" as elsewhere, or "OpenID Provider (OP)" (which appears to be the intent), throughout.

**Review by kjetilk — CHANGES_REQUESTED** [review]
What @TallTed said, other than that, I think it looks good, but it is probably a good idea to have @dmitrizagidulin 's review on it before merging.

**Review by dmitrizagidulin — APPROVED** [review]
👍 from me! :)

**Comment by justinwb** [comment]
Updated based on comments / feedback from @TallTed, @pmcb55, and @kjetilk.

**Review by kjetilk — APPROVED** [review]

**Pull request merged**
